export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const INVALID_LOGIN = 'INVALID_LOGIN';
export const LOAD_FILTERS_SUCCESS = 'LOAD_FILTERS_SUCCESS';
// export const SET_FILTERS_SUCCESS = 'SET_FILTERS_SUCCESS';
