export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const DESTROY_PRODUCT_SUCCESS = 'DESTROY_PRODUCT_SUCCESS';
export const UNSET_FAVORITE_PRODUCT = 'UNSET_FAVORITE_PRODUCT';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
